name: Java Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '18'

    - name: Build with Maven
      run: mvn -B package --file SAS/pom.xml

    - name: Run tests
      run: mvn test --file SAS/pom.xml

    - name: Dockerize
      run: |
        docker build -t nome_da_imagem .
        docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix nome_da_imagem
